### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by srallen** [zooniverse/geordi-client#3]
There really should at least be some integration tests for this, especially if it's going to be added to a front-end client app. We shouldn't have to be concerned with manually testing integration between client and server.

For reference, other clients used on PFE are tested:
[sugar-client's tests](https://github.com/zooniverse/Sugar-Client/tree/master/test)
[panoptes-javascript-client's tests](https://github.com/zooniverse/panoptes-javascript-client/tree/master/test)

**Comment by alexbfree** [comment]
just trying to visualise what this would look like.... something like a simple JS file that instantiates the client, posts to Geordi via the client, and verifies the post made it to Geordi's DB? Which part would be testing - making sure that info passed in as params to the client is correctly passed to geordi?

**Comment by srallen** [comment]
There are javascript testing frameworks. `sugar-client` uses [mocha](https://mochajs.org/) and `panoptes-client` uses [blue-tape](https://www.npmjs.com/package/blue-tape). I don't have a strong opinion on which test runner is used. As far as what to test, there appears to be few methods that can be tested to ensure that we're getting back the expected response. But generally, it doesn't look like very many would need to be written.

**Comment by alexbfree** [comment]
this has now been done
